# This is a basic workflow to help you get started with Actions

name: API Tests using Newman CLI 2
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-api-test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          

      # Install node on runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'


      # Install newman globally, the reporter and the html extra reporter

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          mkdir -p TestArtifact
          

      # Run the Postman collection

     - name: Run Newman
      uses: ./      
      id: run-api-tests
      with:
        collection: "./GITHUB_APITEST.json"
        reporters: cli

    - name: Run Newman - Failure Continue
      uses: ./      
      id: run-api-tests-failure
      with:
        collection: "./GITHUB_APITEST.json"
        reporters: cli
        suppressExitCode: "true"
    
    - name: Export Summary from Outputs
      run: |
        echo ${{ steps.run-api-tests.outputs.summary }}
