name: build-test
'on':
  pull_request: null
  push:
    branches:
      - master
      - releases/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Newman
        uses: ./
        id: run-api-tests
        with:
          collection: ./__tests__/collection.json
          reporters: cli
      - name: Run Newman - Failure Continue
        uses: ./
        id: run-api-tests-failure
        with:
          collection: ./__tests__/collection_failure.json
          reporters: cli
          suppressExitCode: 'true'
      - name: Export Summary from Outputs
        run: |
          echo ${{ steps.run-api-tests.outputs.summary }}
